// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NC_H_FISC.Models
{
    public partial class Banktab
    {
        public string Bankcode { get; set; }
        public string Bankname { get; set; }
        public string Telzone { get; set; }
        public string Telno { get; set; }
        public string Updatedate { get; set; }
    }
}